---
apiVersion: v1
kind: Template
metadata:
  name: ros-backend-pcp-zeroconf
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ros-backend-pcp-zeroconf
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: pcp-generator
      replicas: ${{PCP_GENERATOR_REPLICA_COUNT}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["bash"]
        args: ["-c", "python -m ros.processor.pcp_generator"]
        resources:
          requests:
            cpu: ${CPU_REQUEST_ROSRHEL}
            memory: ${MEMORY_REQUEST_ROSRHEL}
          limits:
            cpu: ${CPU_LIMIT_ROSRHEL}
            memory: ${MEMORY_LIMIT_ROSRHEL}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}

    kafkaTopics:
      - topicName: platform.inventory.events
        partitions: 1

parameters:
- description : ClowdEnvironment name
  name: ENV_NAME
  required: true
- description: Replica count for pcp generator
  name: PCP_GENERATOR_REPLICA_COUNT
  value: "1"
- description: Image NAME
  name: IMAGE
  required: true
  value: quay.io/repository/cloudservices/ros-backend
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Initial cpu request.
  displayName: CPU Request
  name: CPU_REQUEST_ROSRHEL
  required: true
  value: 500m
- description: Initial amount of memory the container will request.
  displayName: Memory Request
  name: MEMORY_REQUEST_ROSRHEL
  required: true
  value: 1Gi
- description: Maximum amount of memory the Django container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT_ROSRHEL
  required: true
  value: 1Gi
- description: Maximum amount of CPU the build container can use.
  displayName: CPU Limit
  name: CPU_LIMIT_ROSRHEL
  required: true
  value: '1'
- description: Is clowder enabled
  name: CLOWDER_ENABLED
  value: "True"
