"""empty message

Revision ID: 0158f7c00beb
Revises: f7fa0888a0ea
Create Date: 2021-02-17 13:56:37.616624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0158f7c00beb'
down_revision = 'f7fa0888a0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_profile', sa.Column('system_id', sa.Integer(), nullable=False))
    op.drop_constraint('performance_profile_inventory_id_report_date_key', 'performance_profile', type_='unique')
    op.create_foreign_key('performance_profile_system_id_fkey', 'performance_profile', 'systems', ['system_id'], ['id'])
    op.drop_column('performance_profile', 'id')
    op.drop_column('performance_profile', 'inventory_id')
    op.create_primary_key('performance_profile_pkey', 'performance_profile', ['system_id', 'report_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('performance_profile_pkey', 'performance_profile')
    op.add_column('performance_profile', sa.Column('inventory_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('performance_profile', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('performance_profile_system_id_fkey', 'performance_profile', type_='foreignkey')
    op.create_unique_constraint('performance_profile_inventory_id_report_date_key', 'performance_profile', ['inventory_id', 'report_date'])
    op.create_primary_key('performance_profile_pkey', 'performance_profile', ['id'])
    op.drop_column('performance_profile', 'system_id')
    # ### end Alembic commands ###
