"""remove unique constraint from account column

Revision ID: 020def9f5b94
Revises: 93262eab7d77
Create Date: 2024-04-18 15:28:09.067224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020def9f5b94'
down_revision = '93262eab7d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rh_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rh_accounts', type_='unique')
        batch_op.create_unique_constraint('uq_rh_accounts', ['org_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rh_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rh_accounts', type_='unique')
        batch_op.create_unique_constraint('uq_rh_accounts', ['account', 'org_id'])

    # ### end Alembic commands ###
