"""empty message

Revision ID: 221edcc12d5c
Revises: 
Create Date: 2020-12-04 12:57:02.775745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '221edcc12d5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('avg_memory_used', sa.String(length=25), nullable=True),
    sa.Column('avg_memory', sa.String(length=25), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_profile')
    # ### end Alembic commands ###
