"""empty message

Revision ID: 290a91f4eff6
Revises: f1fdaf4da40c
Create Date: 2022-08-03 19:24:48.439957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '290a91f4eff6'
down_revision = 'f1fdaf4da40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rh_accounts', 'account',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rh_accounts', 'account',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
