"""added psi enabled

Revision ID: 3fb61393a227
Revises: 290a91f4eff6
Create Date: 2022-10-18 21:47:05.192322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb61393a227'
down_revision = '290a91f4eff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_profile', sa.Column('psi_enabled', sa.Boolean(), nullable=True))
    op.add_column('performance_profile_history', sa.Column('psi_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_profile_history', 'psi_enabled')
    op.drop_column('performance_profile', 'psi_enabled')
    # ### end Alembic commands ###
