"""empty message

Revision ID: 605a688d0cd2
Revises: db7f5df23e1b
Create Date: 2022-02-25 19:42:44.282997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '605a688d0cd2'
down_revision = 'db7f5df23e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('operating_system', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'operating_system')
    # ### end Alembic commands ###
