"""empty message

Revision ID: 6e4bdd2d0450
Revises: 77a3ca142468
Create Date: 2022-07-12 18:55:27.722045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e4bdd2d0450'
down_revision = '77a3ca142468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_profile', 'report_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('rh_accounts', 'account',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rh_accounts', 'account',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('performance_profile', 'report_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
