"""empty message

Revision ID: 744789bd2451
Revises: d1b9d14cd00a
Create Date: 2021-04-06 16:06:20.298585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744789bd2451'
down_revision = 'd1b9d14cd00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    # ### end Alembic commands ###
