"""empty message

Revision ID: 7805dfde3ca9
Revises: ac76a3ecb338
Create Date: 2021-03-10 11:25:26.878848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7805dfde3ca9'
down_revision = 'ac76a3ecb338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('rule_hit_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'rule_hit_details')
    # ### end Alembic commands ###
