"""empty message

Revision ID: 7a2f8d6f27fc
Revises: 0158f7c00beb
Create Date: 2021-02-23 14:49:09.917838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2f8d6f27fc'
down_revision = '0158f7c00beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('cloud_provider', sa.String(length=25), nullable=True))
    op.add_column('systems', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('systems', sa.Column('fqdn', sa.String(length=100), nullable=True))
    op.add_column('systems', sa.Column('instance_type', sa.String(length=25), nullable=True))
    op.add_column('systems', sa.Column('state', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'state')
    op.drop_column('systems', 'instance_type')
    op.drop_column('systems', 'fqdn')
    op.drop_column('systems', 'display_name')
    op.drop_column('systems', 'cloud_provider')
    # ### end Alembic commands ###
