"""create_performance_profile_history_table

Revision ID: 9f16ec63696b
Revises: 605a688d0cd2
Create Date: 2022-03-17 16:18:05.067603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f16ec63696b'
down_revision = '605a688d0cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_profile_history',
    sa.Column('rule_hit_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('operating_system', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_utilization', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('number_of_recommendations', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name='performance_profile_history_system_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id', 'report_date', name='performance_profile_history_pkey')
    )
    op.add_column('performance_profile', sa.Column('state', sa.String(length=25), nullable=True))
    op.add_column('performance_profile', sa.Column('rule_hit_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('performance_profile', sa.Column('operating_system', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('performance_profile', sa.Column('number_of_recommendations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_profile', 'state')
    op.drop_column('performance_profile', 'operating_system')
    op.drop_column('performance_profile', 'rule_hit_details')
    op.drop_column('performance_profile', 'number_of_recommendations')
    op.drop_table('performance_profile_history')
    # ### end Alembic commands ###
