"""empty message

Revision ID: a84856f47314
Revises: d13d58080d80
Create Date: 2022-06-14 15:54:16.902297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a84856f47314'
down_revision = 'd13d58080d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ros_account_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('platform_authentication_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_application_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_source_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_source_type', sa.String(length=25), nullable=False),
    sa.Column('platform_application_is_paused', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ros_account_id'], ['rh_accounts.id'], name='cloud_account_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aws_cloud_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cloud_account_id', sa.BigInteger(), nullable=False),
    sa.Column('aws_account_id', sa.Text(), nullable=False),
    sa.Column('account_arn', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], name='aws_cloud_account_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_arn'),
    sa.UniqueConstraint('aws_account_id')
    )
    op.alter_column('performance_profile', 'report_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_profile', 'report_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_table('aws_cloud_accounts')
    op.drop_table('cloud_accounts')
    # ### end Alembic commands ###
