"""empty message

Revision ID: a983b8b1865d
Revises: d13d58080d80
Create Date: 2022-05-22 11:52:35.335067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a983b8b1865d'
down_revision = 'd13d58080d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('systems_account_id_fkey', 'systems', type_='foreignkey')
    op.alter_column(
        'systems', 'account_id',
        new_column_name='tenant_id'
    )
    op.create_foreign_key('systems_tenant_id_fkey', 'systems', 'rh_accounts', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('systems_tenant_id_fkey', 'systems', type_='foreignkey')
    op.alter_column(
        'systems', 'tenant_id',
        new_column_name='account_id'
    )
    op.create_foreign_key('systems_account_id_fkey', 'systems', 'rh_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
