"""empty message

Revision ID: ac6838d7af60
Revises: 0158f7c00beb
Create Date: 2021-02-24 01:03:02.685857

"""
from alembic import op
import sqlalchemy as sa
from ros.lib.custom_types import IntEnum
from ros.lib.models import RatingChoicesEnum

# revision identifiers, used by Alembic.
revision = 'ac6838d7af60'
down_revision = '0158f7c00beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('rated_by', sa.Text(), nullable=False),
    sa.Column('rating', IntEnum(RatingChoicesEnum), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name='recommendation_rating_system_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_rating')
    # ### end Alembic commands ###
