"""empty message

Revision ID: ac76a3ecb338
Revises: ac6838d7af60
Create Date: 2021-03-03 12:57:15.953877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac76a3ecb338'
down_revision = 'ac6838d7af60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('performance_profile_system_id_fkey', 'performance_profile', type_='foreignkey')
    op.create_foreign_key('performance_profile_system_id_fkey', 'performance_profile', 'systems', ['system_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('performance_profile_system_id_fkey', 'performance_profile', type_='foreignkey')
    op.create_foreign_key('performance_profile_system_id_fkey', 'performance_profile', 'systems', ['system_id'], ['id'])
    # ### end Alembic commands ###
