"""added groups column to systems

Revision ID: b21a2ec1a281
Revises: 42ae31e22f84
Create Date: 2023-06-27 12:09:23.334537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b21a2ec1a281'
down_revision = '42ae31e22f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'groups')
    # ### end Alembic commands ###
