"""Add top_candidate, top_candidate_price on PerformanceProfile

Revision ID: c6f2cd708cea
Revises: 1051e0d7e62e
Create Date: 2023-07-31 19:39:02.205466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f2cd708cea'
down_revision = '1051e0d7e62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_candidate', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('top_candidate_price', sa.Float(), nullable=True))
        batch_op.create_index('top_candidate_idx', ['top_candidate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_profile', schema=None) as batch_op:
        batch_op.drop_index('top_candidate_idx')
        batch_op.drop_column('top_candidate_price')
        batch_op.drop_column('top_candidate')

    # ### end Alembic commands ###
