"""empty message

Revision ID: d13d58080d80
Revises: e65ffbc90def
Create Date: 2022-05-11 16:06:51.909817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd13d58080d80'
down_revision = 'e65ffbc90def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rh_accounts', sa.Column('org_id', sa.Text()))
    op.add_column('systems', sa.Column('rh_org_id', sa.Text()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'rh_org_id')
    op.drop_column('rh_accounts', 'org_id')
    # ### end Alembic commands ###
