"""empty message

Revision ID: d79024110f49
Revises: db7f5df23e1b
Create Date: 2022-01-07 16:52:28.448119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79024110f49'
down_revision = 'db7f5df23e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('release_version', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'release_version')
    # ### end Alembic commands ###
