"""empty message

Revision ID: db7f5df23e1b
Revises: de502e7c8c6a
Create Date: 2021-12-09 18:49:33.616848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7f5df23e1b'
down_revision = 'de502e7c8c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('region', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'region')
    # ### end Alembic commands ###
