"""empty message

Revision ID: e67b2b19df0e
Revises: 0cc86f3e4037
Create Date: 2021-09-02 14:43:40.159163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67b2b19df0e'
down_revision = '0cc86f3e4037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('stale_timestamp', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'stale_timestamp')
    # ### end Alembic commands ###
