"""empty message

Revision ID: f027bd007f0f
Revises: d8648225984f
Create Date: 2021-02-16 19:54:08.860608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f027bd007f0f'
down_revision = 'd8648225984f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_profile', sa.Column('system_id', sa.Integer(), nullable=False))
    op.alter_column('performance_profile', 'report_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint('performance_profile_inventory_id_report_date_key', 'performance_profile', type_='unique')
    op.create_foreign_key('performance_profile_system_id_fkey', 'performance_profile', 'systems', ['system_id'], ['id'])
    op.drop_column('performance_profile', 'inventory_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_profile', sa.Column('inventory_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('performance_profile_system_id_fkey', 'performance_profile', type_='foreignkey')
    op.create_unique_constraint('performance_profile_inventory_id_report_date_key', 'performance_profile', ['inventory_id', 'report_date'])
    op.alter_column('performance_profile', 'report_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('performance_profile', 'system_id')
    # ### end Alembic commands ###
