"""empty message

Revision ID: f0b64806a260
Revises: d1b9d14cd00a
Create Date: 2021-04-05 18:45:56.321738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b64806a260'
down_revision = 'd1b9d14cd00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('number_of_recommendations', sa.Integer(), nullable=True))
    op.add_column('systems', sa.Column('state', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'state')
    op.drop_column('systems', 'number_of_recommendations')
    # ### end Alembic commands ###
