"""empty message

Revision ID: f1fdaf4da40c
Revises: 77a3ca142468
Create Date: 2022-07-08 14:49:44.151908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1fdaf4da40c'
down_revision = '77a3ca142468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_rh_accounts', 'rh_accounts', type_='check')
    op.create_check_constraint('ck_rh_accounts', 'rh_accounts', 'NOT(org_id IS NULL)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_rh_accounts', 'rh_accounts', type_='check')
    op.create_check_constraint('ck_rh_accounts', 'rh_accounts', 'NOT(account IS NULL OR org_id IS NULL)')
    # ### end Alembic commands ###
