{
 "title": "ROS",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "ros-stage, ros-prod" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Current status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Archive Download Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ros_archive_downloaded_success_total{}[24h]))"
    }
   ]
  },
  {
   "title": "Archive Download Failed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(ros_archive_failed_to_download_total{}[24h])) "
    }
   ]
  },
  {
   "title": "Insights Engine pass requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ros_processor_requests_success_total{reporter=~\"INSIGHTS ENGINE\"})"
    }
   ]
  },
  {
   "title": "Total download requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ros_archive_downloaded_success_total or on() vector(0) + ros_archive_failed_to_download_total or on() vector(0))"
    }
   ]
  },
  {
   "title": "Processors Pass Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(ros_processor_requests_success_total{}[24h])) by (reporter)",
     "legendFormat": "{{reporter}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(ros_http_request_total{}[24h])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Backend traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ros_http_request_total{}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "ROS backend requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(increase(ros_http_request_total{job=~\"ros-backend\"}[$__range]))"
    }
   ]
  },
  {
   "title": "ROS backend 2xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ros_http_request_total{job=~\"ros.*\", status=~\"2.*\"}[$__range])) / sum(increase(ros_http_request_total{job=~\"ros.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "ROS backend 5xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ros_http_request_total{job=~\"ros.*\", status=~\"5.*\"}[$__range])) / sum(increase(ros_http_request_total{job=~\"ros.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "ROS backend 4xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ros_http_request_total{job=~\"ros.*\", status=~\"4.*\"}[$__range])) / sum(increase(ros_http_request_total{job=~\"ros.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Kafka Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ros_kafka_failures_total{namespace=~\"$namespace\"}[$__range])) "
    }
   ]
  },
  {
   "title": "CPU consumed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"ros-.*\", namespace=~\"${namespace}\"}[$interval])) by (container)/ sum(kube_pod_container_resource_limits{container=~\"ros-.*\", namespace=~\"${namespace}\", resource=\"cpu\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}