from enum import IntFlag


# From: https://gitlab.cee.redhat.com/pgarciaq/rosrules/-/blob/master/ros_keys.py
class RosKeys(IntFlag):
    OPTIMIZED = 0
    MEMORY_OVERSIZED = 1
    MEMORY_UNDERSIZED = 2
    MEMORY_UNDERSIZED_BY_PRESSURE = 4
    CPU_OVERSIZED = 8
    CPU_UNDERSIZED = 16
    CPU_UNDERSIZED_BY_PRESSURE = 32
    CPU_IDLING = 64
    IO_OVERSIZED = 128
    IO_UNDERSIZED = 256
    IO_UNDERSIZED_BY_PRESSURE = 512
    CONSUMPTION = 1024
    RIGHTSIZING = 2048
    IDLE = 4096


# From: https://gitlab.cee.redhat.com/pgarciaq/rosrules/-/blob/master/ros_thresholds.py
class RosThresholds(object):
    MEMORY_UTILIZATION_WARNING_UPPER_THRESHOLD = 0.8
    MEMORY_UTILIZATION_WARNING_LOWER_THRESHOLD = 0.2
    MEMORY_UTILIZATION_CRITICAL_UPPER_THRESHOLD = 0.95
    MEMORY_UTILIZATION_CRITICAL_LOWER_THRESHOLD = 0.05
    MEMORY_PRESSURE_UPPER_AVERAGE_THRESHOLD = 20.0
    # MEMORY_PRESSURE_LOWER_AVERAGE_THRESHOLD = 0.2
    MEMORY_PRESSURE_FULL_THRESHOLD = 0.0

    CPU_UTILIZATION_WARNING_UPPER_THRESHOLD = 0.8
    CPU_UTILIZATION_WARNING_LOWER_THRESHOLD = 0.2
    CPU_UTILIZATION_CRITICAL_UPPER_THRESHOLD = 0.95
    CPU_UTILIZATION_CRITICAL_LOWER_THRESHOLD = 0.05
    CPU_PRESSURE_UPPER_AVERAGE_THRESHOLD = 20.0
    # CPU_PRESSURE_LOWER_AVERAGE_THRESHOLD = 0.2

    IO_UTILIZATION_WARNING_UPPER_THRESHOLD = 0.8
    IO_UTILIZATION_WARNING_LOWER_THRESHOLD = 0.2
    IO_UTILIZATION_CRITICAL_UPPER_THRESHOLD = 0.95
    IO_UTILIZATION_CRITICAL_LOWER_THRESHOLD = 0.05
    IO_PRESSURE_UPPER_AVERAGE_THRESHOLD = 20.0
    # IO_PRESSURE_LOWER_AVERAGE_THRESHOLD = 0.2
    IO_PRESSURE_FULL_THRESHOLD = 0.0


RosSummary = dict(
    OPTIMIZED='System is OPTIMIZED',
    MEMORY_OVERSIZED='Memory utilization is very low',
    MEMORY_UNDERSIZED='Memory utilization is too high',
    MEMORY_UNDERSIZED_BY_PRESSURE='System is suffering from memory pressure',
    CPU_OVERSIZED='CPU utilization is very low',
    CPU_UNDERSIZED='CPU utilization is too high',
    CPU_UNDERSIZED_BY_PRESSURE='System is suffering from CPU pressure',
    CPU_IDLING='',  # FIXME
    IO_OVERSIZED='I/O utilization is very low',
    IO_UNDERSIZED='I/O utilization is too high',
    IO_UNDERSIZED_BY_PRESSURE='System is suffering from IO pressure',
    CONSUMPTION='',  # FIXME
    RIGHTSIZING='',  # FIXME
    IDLE='System is IDLE',
)
